# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff
        args: [--fix, --config=project-2/pyproject.toml]
      - id: ruff-format
        args: [--config=project-2/pyproject.toml]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        additional_dependencies: [pydantic>=2.0, sqlmodel>=0.0.14, pydantic-settings, types-PyYAML]
        args: [--config-file=project-2/pyproject.toml, --ignore-missing-imports]
        files: ^project-2/
